function testSweeps_copyHTML(fileNameSuffix)

cd(fileparts(which(mfilename)))

fileNameList = {...
    'ConstRadAccFwd_***_qS-35.png',...
    'ConstRadAccFwd_***_qS35.png',...
    'ConstRadAccRev_***_qS-35.png',...
    'ConstRadAccRev_***_qS35.png',...
    'MastLift_***_Map.png',...
    'Static_***_Map.png',...
    'StepSteerFwdL_***_Map.png',...
    'StepSteerFwdR_***_Map.png',...
    'StepSteerRevL_***_Map.png',...
    'StepSteerRevR_***_Map.png',...
    };

for fi = 1:length(fileNameList)
    fOrig = strrep(fileNameList{fi},'***',fileNameSuffix);
    fNew  = strrep(fileNameList{fi},'***_','');
    copyfile([pwd filesep 'Test_' fileNameSuffix filesep fOrig],[pwd filesep 'Example' filesep fNew])
end

testSweeps_createHTML('');
